kind: Service
apiVersion: v1
metadata:
  name: helloworld
  namespace: default
spec:
  selector:
    app: pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 35.205.31.127


